### ISSUE TITLE
How to modify the scale of maze?

### ISSUE THREAD

**Issue by EdXian** [PeterMitrano/gzmaze#1]
hi Peter , 
I want to use my robot to solve the maze problem but the maze is too small for my robot. how do i modify the scale of maze. 
thanks!!

**Comment by PeterMitrano** [comment]
You'll need to change the base SDF, and any constants in [here](https://github.com/PeterMitrano/gzmaze/blob/master/maze_plugin/MazePlugin.cc) you see fit

**Comment by EdXian** [comment]
Thanks Peter,
It's helpful. I got the desired maze!!
